'use strict';

function val(str) {
    return parseFloat(str.replace(/\./g, '').replace(',', '.').replace('%', ''));
}

module.exports = (values) => {
    return {
        papel: values[0].data,
        data: values[3].data,
        empresa: values[4].data,
        setor: values[6].data,
        subsetor: values[8].data,
        contacao: val(values[1].data),
        min_52_sem: val(values[5].data),
        max_52_sem: val(values[7].data),
        vol_med_2m: val(values[9].data),
        ult_balanco_processado: values[11].data,
        valor_da_firma: val(values[12].data),
        nro_acoes: val(values[13].data),
        dia: val(values[14].data),
        p_l: val(values[15].data),
        lpa: val(values[16].data),
        mes: val(values[17].data),
        p_vp: val(values[18].data),
        vpa: val(values[19].data),
        trinta_dias: val(values[20].data),
        p_ebit: val(values[21].data),
        marg_bruta: val(values[22].data),
        doze_meses: val(values[23].data),
        psr: val(values[24].data),
        marg_ebit: val(values[25].data),
        ano_2020: val(values[26].data),
        p_ativos: val(values[27].data),
        marg_liquida: val(values[28].data),
        ano_2019: val(values[29].data),
        p_cap_giro: val(values[30].data),
        ebit_ativo: val(values[31].data),
        ano_2018: val(values[32].data),
        p_ativ_circ_liq: val(values[33].data),
        roic: val(values[34].data),
        ano_2017: val(values[35].data),
        div_yield: val(values[36].data),
        roe: val(values[37].data),
        ano_2016: val(values[38].data),
        ev_ebitda: val(values[39].data),
        liquidez_corr: val(values[40].data),
        ano_2015: val(values[41].data),
        ev_ebit: val(values[42].data),
        div_br_patrim: val(values[43].data),
        cres_rec_5a: val(values[45].data),
        giro_ativos: val(values[46].data),
        ativo: val(values[47].data),
        div_bruta: val(values[48].data),
        disponibilidades: val(values[49].data),
        div_liquida: val(values[50].data),
        ativo_circulante: val(values[51].data),
        patrim_liq: val(values[52].data),
        receita_liquida: val(values[53].data),
        receita_liquida: val(values[54].data),
        ebit: val(values[55].data),
        ebit: val(values[56].data),
        lucro_liquido: val(values[57].data),
        lucro_liquido: val(values[58].data),
    };
}
